# aaa・bbbのlambda artifactの生成とデプロイを行うWorkflow
# developブランチの変更もしくは手動で起動します

name: deploy

on:
  workflow_dispatch:
  push:
    paths:
      - "app/aaa/**"
      - "app/bbb/**"
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      aaa: ${{ steps.filter.outputs.aaa }}
      bbb: ${{ steps.filter.outputs.bbb }}
    steps:
      - uses: dorny/paths-filter@v3
        name: Paths Filter
        id: filter
        with:
          filters: |
            aaa:
              - "app/aaa/**"
            bbb:
              - "app/bbb/**"

  decision-working-directory:
    name: Decision Working Directory
    needs: changes
    runs-on: ubuntu-latest
    outputs:
      target-working-directory: ${{ steps.decision.outputs.working-directory }}
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Decision aaa
        id: decision
        if: ${{ needs.changes.outputs.aaa == 'true' }}
        run: echo "working-directory=app/lambda/aaa" >> $GITHUB_OUTPUT
      # aaa
      - name: Decision bbb
        id: decision
        if: ${{ needs.changes.outputs.bbb == 'true' }}
        run: echo "working-directory=app/lambda/bbb" >> $GITHUB_OUTPUT

  deploy:
    name: deploy_job_name
    needs: decision-working-directory
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ needs.decision-working-directory.outputs.target-working-directory }}

    steps:
      - uses: actions/checkout@v4.1.2
      # aaaa
      - name: step-test
      run: echo "${{ needs.decision-working-directory.outputs.target-working-directory }}"
