name: lambda-deploy

on:
  workflow_dispatch:
  push:
    paths:
      - "app/aaa/**"
      - "app/bbb/**"
      - "app/ccc/**"
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      aaa: ${{ steps.filter.outputs.aaa }}
      bbb: ${{ steps.filter.outputs.bbb }}
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: dorny/paths-filter@v3
        name: Paths Filter
        id: filter
        with:
          filters: |
            aaa:
              - "app/aaa/**"
              - "app/ccc/**"
            bbb:
              - "app/bbb/**"
              - "app/ccc/**"

  deploy-aaa:
    name: deploy-aaa
    needs: changes
    if: ${{ needs.changes.outputs.aaa == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/aaa

    steps:
      - uses: actions/checkout@v4.1.2
      - name: Decision bbb
        run: pwd

  deploy-bbb:
    name: deploy-bbb
    needs: changes
    if: ${{ needs.changes.outputs.bbb == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/bbb

    steps:
      - uses: actions/checkout@v4.1.2
      - name: Decision bbb
        run: pwd
